

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.9.2
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: "wrBAY8Gyq97qc1eAv04MCsLmbHiwgyOVafEFC54DpEs="
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
      AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_ENABLED: "true"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    entrypoint: >
      bash -c "airflow db upgrade && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@admin.com"
      
  scheduler:
    image: apache/airflow:2.9.2
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: "wrBAY8Gyq97qc1eAv04MCsLmbHiwgyOVafEFC54DpEs="
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
      AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_ENABLED: "true"
      DBT_PROFILES_DIR: /opt/airflow/.dbt
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./analytics:/opt/airflow/analytics
      - ./.dbt:/opt/airflow/.dbt
    command: scheduler
  airflow:
    image: apache/airflow:2.9.2
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: "wrBAY8Gyq97qc1eAv04MCsLmbHiwgyOVafEFC54DpEs="
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
      AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_ENABLED: "true"
      DBT_PROFILES_DIR: /opt/airflow/.dbt
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./analytics:/opt/airflow/analytics
      - ./.dbt:/opt/airflow/.dbt
    command: webserver

volumes:
  pgdata:
